
#FROM centos
FROM  greshem_scm_base_common
MAINTAINER greshem
#RUN yum install epel-release  
RUN yum install -y  ctags dos2unix file 

COPY        ./  /tmp/global 
RUN mkdir /src/

WORKDIR     ~/global-4.4_logger/
RUN  bash install.sh 

USER 0
#EXPOSE      22222
ENTRYPOINT [  "/tmp/global/entrypoint.sh" ] 
