
# ~/greshem_images_dockerfiles/greshem_base_common/build.sh
# ~/greshem_images_dockerfiles/greshem_base_common/dockerfile 

# ~/greshem_images_dockerfiles/greshem_base_python/build.sh 
# ~/greshem_images_dockerfiles/greshem_base_python/dockerfile 

#FROM centos:7
#MAINTAINER greshem
#RUN yum install epel-release -y && yum clean all
#RUN yum update -y && yum clean all
#RUN yum install -y yum-utils yum-plugin-ovl tar  curl  unzip wget  python-pip mysql-devel   gcc  python-devel  && yum clean all 
#FROM  greshem/greshem_scm_base

#FROM  greshem/greshem_scm_base_common
FROM  python37:centos7

#RUN yum install -y  python36  python3-pip  python-django pytz 
COPY        ./  /opt/gentelella_django 
WORKDIR     /opt/gentelella_django/
RUN         pip install   --trusted-host  pypi.douban.com  -i http://pypi.douban.com/simple/     -r  requirements.txt 

USER 0
EXPOSE      8000
CMD [  "/opt/gentelella_django/entrypoint.sh" ] 
#ENTRYPOINT [  "/opt/gentelella_django/entrypoint.sh" ] 
