FROM  greshem/python36_build_env:centos7  
MAINTAINER greshem

ADD ./ /opt/src/
WORKDIR /opt/src/
#RUN   pip3.6 install -r req.txt 


 RUN  pip3.6 install TensorFlow==1.3.0
 RUN  pip3.6 install Keras==2.0.8
 RUN  pip3.6 install NumPy==1.13.3
 RUN  pip3.6 install Pillow==4.2.1
 RUN  pip3.6 install Pandas==0.18.0
 RUN  pip3.6 install Scikit-learn==0.19.0
 RUN  pip3.6 install h5py==2.7.1
