#FROM  127.0.0.1:5000/dnsmasq:latest
#FROM  127.0.0.1:5001/docker.io/centos
#FROM centos
FROM  greshem/greshem_scm_base_common
RUN  yum install -y python34
RUN  mkdir /tmp/data/
EXPOSE 33336

USER 1001


#ENTRYPOINT [  "cd","/data", "&&","/usr/bin/python",  "-m", "SimpleHTTPServer",  "33336",  "/data " ]
#   python3 -m http.server 33336

WORKDIR  /data/
ENTRYPOINT [  "/usr/bin/python3",  "-m", "http.server",   "33336"    ]



