apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: sameersbn/postgresql:9.5-3
    generation: null
    importPolicy: {}
    name: 9.5-3
status:
  dockerImageRepository: ""
