FROM  greshem/greshem_scm_base_common
MAINTAINER greshem
#yum  -y install https://mirrors.aliyun.com/zabbix/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm





#Setting up systemd
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
ENTRYPOINT ["/usr/sbin/init"]
 

RUN yum install -y systemd* && yum clean all
RUN yum install -y zabbix-server-mysql mariadb-server zabbix-agent php zabbix-web-mysql.noarch    
RUN yum install -y zabbix-server-mysql-3.4.15-1.el7.x86_64  zabbix-web-mysql-3.4.15-1.el7   
RUN yum install -y initscripts && yum clean all

#RUN mkdir /tmp/zabbix/
COPY        ./  /opt/zabbix/
WORKDIR     /opt/zabbix/
#RUN  bash  entrypoint.sh 

USER 0
EXPOSE      80

RUN systemctl enable mariadb 
RUN systemctl enable httpd
RUN systemctl enable  zabbix-server.service

ENV PS1 "[\u@zabbixsrv \W]# "
EXPOSE 80
EXPOSE 10051

